services:
  - type: web
    name: mutant-detector
    env: docker
    plan: free
    branch: main
    autoDeploy: true
    dockerfilePath: Dockerfile
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: PORT
        value: 8080
